// CreatureQuest — Mock data for demo/simulation

import type {
  Creature,
  Agent,
  CombatEvent,
  Enemy,
  MarketListing,
  LeaderboardEntry,
  ZoneInfo,
  PlayerStats,
} from "./types";

export const ZONES: ZoneInfo[] = [
  {
    id: "forest",
    name: "Verdant Forest",
    description: "A lush starting zone teeming with weak slimes and herb nodes.",
    minLevel: 1,
    difficulty: "easy",
    enemyTypes: ["Slime", "Forest Sprite", "Mushling"],
    activeAgents: 234,
    icon: "🌲",
    bgColor: "from-emerald-900 to-green-950",
    resources: ["Herb", "Wood", "Slime Jelly"],
    tokenMultiplier: 1.0,
  },
  {
    id: "cave",
    name: "Crystal Caverns",
    description: "Dark tunnels with tougher monsters but better loot.",
    minLevel: 10,
    difficulty: "medium",
    enemyTypes: ["Cave Bat", "Stone Golem", "Crystal Crab"],
    activeAgents: 128,
    icon: "🪨",
    bgColor: "from-slate-900 to-gray-950",
    resources: ["Crystal", "Iron Ore", "Bat Wing"],
    tokenMultiplier: 2.5,
  },
  {
    id: "dungeon",
    name: "Abyssal Dungeon",
    description: "Extreme danger, extreme rewards. Not for the faint of heart.",
    minLevel: 25,
    difficulty: "extreme",
    enemyTypes: ["Shadow Demon", "Bone Dragon", "Void Wraith"],
    activeAgents: 47,
    icon: "💀",
    bgColor: "from-purple-950 to-violet-950",
    resources: ["Void Shard", "Dragon Scale", "Dark Essence"],
    tokenMultiplier: 10.0,
  },
  {
    id: "town",
    name: "Ember Town",
    description: "Safe haven. Trade, breed, and plan your next expedition.",
    minLevel: 0,
    difficulty: "easy",
    enemyTypes: [],
    activeAgents: 512,
    icon: "🏘️",
    bgColor: "from-amber-900 to-orange-950",
    resources: [],
    tokenMultiplier: 0,
  },
];

export const MOCK_CREATURES: Creature[] = [
  {
    id: "c1",
    tokenId: 4291,
    name: "Thornbark",
    class: "plant",
    rarity: "epic",
    level: 18,
    exp: 32400,
    expToNext: 36100,
    stats: { hp: 890, maxHp: 1000, attack: 78, speed: 62, defense: 112 },
    parts: { body: "Mossy Bark", head: "Leaf Crown", tail: "Vine Whip", horn: "Thorn Spike", wings: null },
    skills: [
      { id: "leaf_blade", name: "Leaf Blade", damage: 85, cooldown: 3, cdRemaining: 0, type: "attack", icon: "🌿" },
      { id: "vine_wrap", name: "Vine Wrap", damage: 40, cooldown: 5, cdRemaining: 2, type: "attack", icon: "🪴" },
      { id: "photosynthesis", name: "Photosynthesis", damage: -60, cooldown: 8, cdRemaining: 0, type: "heal", icon: "☀️" },
    ],
    breedCount: 2,
    maxBreeds: 7,
    isEvolved: false,
    imageEmoji: "🌿",
  },
  {
    id: "c2",
    tokenId: 7823,
    name: "Crimson Fang",
    class: "beast",
    rarity: "rare",
    level: 12,
    exp: 14400,
    expToNext: 16900,
    stats: { hp: 640, maxHp: 800, attack: 115, speed: 88, defense: 62 },
    parts: { body: "Scarlet Fur", head: "Fanged Jaw", tail: "Blade Tail", horn: "Twin Horns", wings: "Feral Wings" },
    skills: [
      { id: "savage_bite", name: "Savage Bite", damage: 110, cooldown: 2, cdRemaining: 0, type: "attack", icon: "🦷" },
      { id: "blood_frenzy", name: "Blood Frenzy", damage: 150, cooldown: 6, cdRemaining: 0, type: "attack", icon: "🩸" },
    ],
    breedCount: 0,
    maxBreeds: 7,
    isEvolved: true,
    imageEmoji: "🦊",
  },
  {
    id: "c3",
    tokenId: 1105,
    name: "Pearlshell",
    class: "aqua",
    rarity: "legendary",
    level: 31,
    exp: 96100,
    expToNext: 102400,
    stats: { hp: 980, maxHp: 1100, attack: 96, speed: 134, defense: 78 },
    parts: { body: "Pearl Shell", head: "Coral Crown", tail: "Sea Whip", horn: "Trident Horn", wings: "Fin Wings" },
    skills: [
      { id: "tidal_wave", name: "Tidal Wave", damage: 140, cooldown: 4, cdRemaining: 1, type: "attack", icon: "🌊" },
      { id: "bubble_burst", name: "Bubble Burst", damage: 60, cooldown: 2, cdRemaining: 0, type: "attack", icon: "🫧" },
      { id: "ocean_mend", name: "Ocean Mend", damage: -80, cooldown: 7, cdRemaining: 0, type: "heal", icon: "💙" },
    ],
    breedCount: 5,
    maxBreeds: 7,
    isEvolved: true,
    imageEmoji: "🐚",
  },
];

export const MOCK_AGENTS: Agent[] = [
  {
    id: "a1",
    creatureId: "c1",
    state: "attacking",
    strategy: "farming",
    personality: { aggression: 60, greed: 75, riskTolerance: 40 },
    memory: { totalTokensEarned: 12847, battlesWon: 384, battlesLost: 23, bestZone: "forest", sessionsRun: 47 },
    currentZone: "forest",
    isActive: true,
    lastTickAt: Date.now() - 200,
    tokensThisSession: 234,
    behaviorHash: "QmX7fN...a4kR",
  },
  {
    id: "a2",
    creatureId: "c2",
    state: "looting",
    strategy: "hunting",
    personality: { aggression: 90, greed: 55, riskTolerance: 80 },
    memory: { totalTokensEarned: 8932, battlesWon: 612, battlesLost: 78, bestZone: "cave", sessionsRun: 31 },
    currentZone: "cave",
    isActive: true,
    lastTickAt: Date.now() - 200,
    tokensThisSession: 891,
    behaviorHash: "QmY3zP...b8mW",
  },
  {
    id: "a3",
    creatureId: "c3",
    state: "idle",
    strategy: "exploring",
    personality: { aggression: 45, greed: 30, riskTolerance: 95 },
    memory: { totalTokensEarned: 41203, battlesWon: 1205, battlesLost: 31, bestZone: "dungeon", sessionsRun: 89 },
    currentZone: "dungeon",
    isActive: false,
    lastTickAt: Date.now() - 60000,
    tokensThisSession: 0,
    behaviorHash: "QmZ9wQ...c2xL",
  },
];

// Factory function — called on client to avoid SSR/hydration timestamp mismatch
export function makeMockCombatLog(): CombatEvent[] {
  const t = Date.now();
  return [
    { id: "e1", timestamp: t - 2000,  attacker: "Thornbark",    target: "Forest Slime",  damage: 82,  isCrit: false, skillUsed: "Leaf Blade",   targetDied: true,  tokensEarned: 3.2,   zone: "forest" },
    { id: "e2", timestamp: t - 4500,  attacker: "Crimson Fang", target: "Stone Golem",   damage: 218, isCrit: true,  skillUsed: "Blood Frenzy", targetDied: true,  tokensEarned: 18.5,  zone: "cave" },
    { id: "e3", timestamp: t - 7000,  attacker: "Thornbark",    target: "Forest Sprite", damage: 45,  isCrit: false, skillUsed: null,            targetDied: false, tokensEarned: 0,     zone: "forest" },
    { id: "e4", timestamp: t - 9200,  attacker: "Thornbark",    target: "Forest Sprite", damage: 61,  isCrit: false, skillUsed: "Leaf Blade",   targetDied: true,  tokensEarned: 2.8,   zone: "forest" },
    { id: "e5", timestamp: t - 14000, attacker: "Crimson Fang", target: "Cave Bat",      damage: 95,  isCrit: false, skillUsed: "Savage Bite",  targetDied: true,  tokensEarned: 7.1,   zone: "cave" },
    { id: "e6", timestamp: t - 18000, attacker: "Thornbark",    target: "Mushling",      damage: 73,  isCrit: false, skillUsed: null,            targetDied: true,  tokensEarned: 1.9,   zone: "forest" },
    { id: "e7", timestamp: t - 22000, attacker: "Pearlshell",   target: "Void Wraith",   damage: 411, isCrit: true,  skillUsed: "Tidal Wave",   targetDied: true,  tokensEarned: 142.0, zone: "dungeon" },
  ];
}

// Keep a static export for non-time-sensitive use
export const MOCK_COMBAT_LOG: CombatEvent[] = makeMockCombatLog();

export const MOCK_MARKET: MarketListing[] = [
  {
    id: "m1",
    sellerAddress: "0x1a2b3c",
    sellerName: "NightTrader",
    itemType: "creature",
    creature: {
      id: "cx1",
      tokenId: 9901,
      name: "Viper Rush",
      class: "reptile",
      rarity: "epic",
      level: 22,
      exp: 48400,
      expToNext: 52900,
      stats: { hp: 820, maxHp: 900, attack: 108, speed: 142, defense: 55 },
      parts: { body: "Scale Armor", head: "Viper Hood", tail: "Spike Tail", horn: "Fang Horn", wings: null },
      skills: [],
      breedCount: 1,
      maxBreeds: 7,
      isEvolved: false,
      imageEmoji: "🐍",
    },
    priceQuest: 8500,
    listedAt: Date.now() - 3600000,
  },
  {
    id: "m2",
    sellerAddress: "0x4d5e6f",
    sellerName: "CryptoFarmer",
    itemType: "material",
    itemName: "Dragon Scale x10",
    itemIcon: "🐉",
    priceQuest: 2200,
    listedAt: Date.now() - 7200000,
  },
  {
    id: "m3",
    sellerAddress: "0x7g8h9i",
    sellerName: "GuildMaster",
    itemType: "creature",
    creature: {
      id: "cx2",
      tokenId: 3344,
      name: "Blazewing",
      class: "beast",
      rarity: "legendary",
      level: 45,
      exp: 202500,
      expToNext: 216000,
      stats: { hp: 1300, maxHp: 1300, attack: 188, speed: 156, defense: 92 },
      parts: { body: "Fire Pelt", head: "Blaze Mane", tail: "Flame Tail", horn: "Ember Horn", wings: "Inferno Wings" },
      skills: [],
      breedCount: 3,
      maxBreeds: 7,
      isEvolved: true,
      imageEmoji: "🔥",
    },
    priceQuest: 95000,
    listedAt: Date.now() - 900000,
  },
  {
    id: "m4",
    sellerAddress: "0x2k3l4m",
    sellerName: "AquaBreeder",
    itemType: "material",
    itemName: "Void Shard x5",
    itemIcon: "🔮",
    priceQuest: 5800,
    listedAt: Date.now() - 10800000,
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, ownerAddress: "0xabc123", ownerName: "AquaLord", ownerAvatar: "🏆", agentId: "top1", creatureName: "Pearlshell", creatureClass: "aqua", tokensEarned: 284920, battlesWon: 4821, level: 67, strategy: "hunting" },
  { rank: 2, ownerAddress: "0xdef456", ownerName: "BeastKing", ownerAvatar: "🥈", agentId: "top2", creatureName: "Blazewing", creatureClass: "beast", tokensEarned: 198341, battlesWon: 3956, level: 58, strategy: "hunting" },
  { rank: 3, ownerAddress: "0xghi789", ownerName: "PlantMage", ownerAvatar: "🥉", agentId: "top3", creatureName: "Thornwood Elder", creatureClass: "plant", tokensEarned: 134210, battlesWon: 2847, level: 52, strategy: "farming" },
  { rank: 4, ownerAddress: "0xjkl012", ownerName: "ShadowFarm", ownerAvatar: "⚔️", agentId: "top4", creatureName: "Nightcrawler", creatureClass: "bug", tokensEarned: 87456, battlesWon: 2112, level: 44, strategy: "farming" },
  { rank: 5, ownerAddress: "0xmno345", ownerName: "DungeonLord", ownerAvatar: "💎", agentId: "top5", creatureName: "Voidscale", creatureClass: "reptile", tokensEarned: 71839, battlesWon: 1920, level: 41, strategy: "exploring" },
  { rank: 6, ownerAddress: "0xpqr678", ownerName: "CryptoFarmer", ownerAvatar: "🌾", agentId: "top6", creatureName: "Mosswarden", creatureClass: "plant", tokensEarned: 54228, battlesWon: 1445, level: 38, strategy: "farming" },
  { rank: 7, ownerAddress: "0xstu901", ownerName: "TokenHunter", ownerAvatar: "🎯", agentId: "top7", creatureName: "Swiftclaw", creatureClass: "beast", tokensEarned: 42891, battlesWon: 1203, level: 35, strategy: "hunting" },
];

export const MOCK_PLAYER_STATS: PlayerStats = {
  totalCreatures: 3,
  activeAgents: 2,
  totalTokensEarned: 63982,
  totalBattlesWon: 2201,
  highestCreatureLevel: 31,
  favoriteZone: "forest",
};
